import RedirectLink from "@/views/Homepage/components/RedirectLink"
import { SwapRightOutlined } from "@ant-design/icons"

const SaleDetail = () => {
  return (
    <div className="info-section background-fade pb-20 mb-16">
      <div className="container-sm">
        <div className="mt-[70px] mx-8 lg:mx-0 ">
          <h2 className="font-bold mb-6 text-[#ededed] text-center">Sale Detail</h2>
          <div className="flex flex-col mb-8">
            <p className="font-bold text-[18px]">The first NFT sale on zkSync</p>
            <span className="font-light text-[16px] leading-6">Start: 2023–05–13 12:00pm(UTC)</span>
            <span className="font-light text-[16px] leading-6">End: 2023–05–14 15:00pm(UTC)</span>
            <span className="font-light text-[16px] leading-6">Quantity: 2,450</span>
            <span className="font-light text-[16px] leading-6">*Unsold NFTs will be burned.</span>
          </div>
          <div className="flex flex-col mb-8">
            <p className="font-bold text-[18px]">The second NFT sale on Arbitrum</p>
            <span className="font-light text-[16px] leading-6">Start: 2023–05–20 12:00pm(UTC)</span>
            <span className="font-light text-[16px] leading-6">End: 2023–05–21 15:00pm(UTC)</span>
            <span className="font-light text-[16px] leading-6">Quantity: 2,450</span>
            <span className="font-light text-[16px] leading-6">*Unsold NFTs will be burned.</span>
          </div>
          <div className="flex flex-col rtl">
            <p className="font-bold text-[18px]">astSecretkey Benefits</p>
            <ul className="list-outside list-disc marker:text-[21px] md:mx-0 mx-4 font-light text-[16px] p-0 leading-6">
              <li><span className="relative -left-1 align-text-bottom">Entitle you to a share of trading fees generated by Asterisk(20–10%).</span></li>
              <li><span className="relative -left-1 align-text-bottom">The royalty charged from secondary sales is 8%, with 4% going to a pool that the original minters can claim indefinitely, and the other 4% going to the astSecretkey staking pool.</span></li>
              <li><span className="relative -left-1 align-text-bottom">Guarantee you an Asterisk fair launch airdrop (5M).</span></li>
              <li><span className="relative -left-1 align-text-bottom">You can earn the FCFS Mega Bonus (5M).</span></li>
              <li><span className="relative -left-1 align-text-bottom">You can participate in the AST Treasure-hunt.</span></li>
              <li><span className="relative -left-1 align-text-bottom">Additionally, you can receive other privileges in the future.</span></li>
            </ul>
          </div>
          <div className='flex justify-end items-center mt-[10px]'>
            <SwapRightOutlined className="text-[30px] md:mr-0 mr-[20px]"/>
            <RedirectLink link="https://medium.com/@asterisk.finance/sale-detail-797d4056c8de" title="More Detail" />
          </div>
        </div>
      </div>
    </div>
  )
}

export default SaleDetail